module.exports = `DONE
└─3
  └─2
    └─1
└─EOF
  └─entryC10
    └─entryB10
      └─entryA10
    └─entryC9
      └─entryB9
        └─entryA9
      └─entryC8
        └─entryB8
          └─entryA8
        └─entryC7
          └─entryB7
            └─entryA7
          └─entryC6
            └─entryB6
              └─entryA6
            └─entryC5
              └─entryB5
                └─entryA5
              └─entryC4
                └─entryB4
                  └─entryA4
                └─entryC3
                  └─entryB3
                    └─entryA3
                  └─entryC2
                    └─entryB2
                      └─entryA2
                    └─entryC1
                      └─entryB1
                        └─entryA1`
